name: Build and generate docs

on:
  push:
    branches-ignore:
      - docs
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        java: [ 17 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-package: jdk
          java-version: ${{ matrix.java }}

      - name: Make Gradle executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x gradlew

      - name: Test using Gradle
        run: ./gradlew test --info

      - name: Build using Gradle
        run: ./gradlew build

      - name: Generate docs using Gradle
        run: ./gradlew dokkaHtmlMultiModule

      - name: Extract branch name
        id: extract_branch
        if: ${{ github.event_name == 'push' }}  # Only deploy docs if we're pushing
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"

      - name: Deploy documentation
        if: ${{ github.event_name == 'push' }}  # Only deploy docs if we're pushing
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/dokka/htmlMultiModule
          cname: docs.mizu.wtf
          publish_branch: docs-${{ steps.extract_branch.outputs.branch }}
          force_orphan: true
